'use strict';

// list of coffee producing countries that need to be included in the map (leave out hawaii)
var coffeeCountries = ['Burundi', 
					  'Ethiopia', 
					  'Kenya', 
					  'Malawi', 
					  'Rwanda', 
					  'Tanzania', 
					  'Zambia', 
					  'Bolivia', 
					  'Brazil', 
					  'Colombia',
					  'Costa Rica',
					  'Cuba',
					  'Dominican Republic',
					  'Ecuador',
					  'El Salvador',
					  'Guatemala',
					  'Honduras',
					  'Jamaica',
					  'Mexico',
					  'Nicaragua',
					  'Panama',
					  'Peru',
					  'Venezuela',
					  'India',
					  'Indonesia',
					  'Papua New Guinea',
					  'Vietnam',
					  'Yemen'];


// pieces of text that will be used to show as main information on the selected 'wave'
var mainTexts = {first: 'Long, long ago, in the far-away Ethiopian highlands, lived a goatherd. His name was Kaldi, and one day he noticed his goats dancing and staying awake all through the night after eating the berries from a certain plant. Kaldi told the abbot at the local monastery about his findings, and the abbot and the other monks started exploring this unique berry and its effects. Although this story is just a myth and can not be confirmed, coffee does originate from Ethiopia.',
			 	second: 'After the discovery of the coffee in Ethiopia and its cultivation all over the world, coffee had become indispensable in the daily routine of many people around the world. The coffee houses were places where people met to talk about all sorts of things, from day-to-day stuff to important strategic decisions. And although there were differences, almost all coffee was made using a filtering technique; the roasted beans were grinded and the coffee was extracted using hot water. Espresso started growing in popularity around the world from around 1950, thereby ushering the second wave of coffee.',
			 	third: 'Initialised by Starbucks around 1990, companies started direct-trading with farmers to ensure the highest possible quality of the coffee, and to find and create particular flavours. Aspects such as the origin of a coffee, process-methods and what variety it belonged to became more important than ever. Over 40 different varietes have already been discovered, and still new varieties are discovered or created, all with their own unique charactaristics. With this focus for detail about the bean and the processes that were involved, came a new interest in extraction methods, too. Espresso, although still by far the most sold coffee in coffeehouses today, was not the only way to make coffee anymore. New techniques were discovered and old ones rediscovered. The new focus on \'filter coffees\' also let to new ways of roasting; instead of dark espresso roasts, used to bring out the sweetness and bitterness in coffee (the high pressure of an espresso machine increases the level of acidity in coffee, so this needs to be balanced out), a filter coffee roast could be lighter, fruitier and greener. Most filter methods do not use any form of (high) pressure, thus leading to a calmer extraction, and very little distorted flavours.',
			 	fourth: 'Coffee has always been a very popular beverage, one of the most popular in the world. What is different now, compared to before, is not just the focus on a very unique cup of coffee; it is also the focus on letting people experience coffee outside of the usual coffee bars and roasteries, at places such as large events or at home. This change in attitude towards coffee might be the beginning of the fourth wave; a period where it is not just about creating the \'best coffee\', but instead, about exploring all of the different flavours that are available, what different roasts do to different coffees, what extraction techniques result in what flavours, and sharing this knowledge with the rest of the world. For this wave, the map will show something different: for every coffee producing country, information is available on the varieties that are common and what flavour characteristics are unique for the area.'};

// pieces of text that will be used to put in the toolTip on mouseover a specific country
var popUpTexts = {netherlands: 'Because the Arabs only sold roasted beans, the Netherlands, among other European countries, were not able to cultivate coffee themselves. This monopoly came to an end when a trader from the Dutch East Indian Company, Pieter van der Broecke, managed to \'obtain\' (some sources say \'steal\') some coffee plants from Yemen in 1616. These plants grew so well in the Amsterdam Botanical Gardens, that in 1658 the first \'Coffea Arabica\' was being cultivated in Ceylon(Sri Lanka) and not much later also in other Dutch colonies, such as India, Java (Indonesia) and Suriname. ',
				 france: 'Although the Dutch were the first to cultivate coffee outside of the Arabian Peninsula, the French were the ones who exported it to biggest coffee-producing country in the world, Brazil. Back in 1714, the Mayor of Amsterdam gave King Louise XIV of France a coffee plant, as a present to grow in the Paris Royal Botanical Gardens. Some of the seeds of this plant were taken by Gabriel de Clieu in 1723 and brought to Martinique, one of the French colonies at that time. Most of the coffee that is being grown in Middle and Southern America today originates from those seeds. ',
				 arabPeninsula: 'After its discovery in Ethiopia, the Arabs were the first to cultivate and trade coffee. This was around 14th century, and for next couple of hundred years, the Arabs held a monopoly on coffeetrade. In the 15th century it was mainly grown in the Yemeni district of Arabia, but by the 16th century coffee was being drunk in Persia, Turkey, Egypt and Syria. This also led to the creation of the first coffee houses, of which the first one was reported to be located at Constantinopel in 1475, and was called \'Kiva Han\'.',
				 italy: 'An espresso was made with a different technique. A small amount of water was pushed through coffeegrounds. This technique was first patented by Angelo Moriono in Turin in 1884, and the espresso machine has been perfected ever after. Espresso was a very popular drink, not just because the drink itself, but also because the variations that came with it, such as the cappuccino, which is an espresso with foamed milk. This version was particulary popular outside of Italy itself, mainly in Gread Britain. In Italy, espresso was a beverage for the working-class, and the price of a single espresso, if you were standing at the bar while drinking it, was being regulated by the government, and thus keeping it very, very affordable.',
				 unitedStatesSecond: 'Although espresso was already known in the United States, it wasn\'t a well known drink until the 1990\'s. From 1820 until then, coffee had been the most popular drink in the United States, but nobody had given much care to the production of it. As long as it had a lot of caffeine in it and kept you awake, it did not really matter how it tasted. There even was instant-coffee (not just in the United States, most coffee drinkers around the world did not care much for the flavour or origin of coffee). All of this changed when Howard Schultz came to Starbucks in 1982. Howard Schultz, inspired by the Italian espresso culture, introduced espresso and lots of different espresso-based drinks. The success this has brought Starbucks has been immense, quickly conquering the US and most of Western Europe. Starbucks also introduced something important; they were the first who started direct-trading with the farmers at a global scale. Instead of buying their coffee on world market for coffee, they started paying more for a certain variation of coffee, grown at a specific farm in a specific region of a specific country, and working together with the farmers to create, in their eyes, a perfect coffeebean.',
				 westernEurope: 'A very experimental coffee culture, similar to the Scandinavian culture. Some people use more Australian roasts, some use more Scandinavian roasts, although the main trend lies more towards the lighter, Nordic roasts. The coffee culture is in a very developed stadium here. Every (major) city has lots of coffeehouses, and there are different kind of places for different needs; from small roasteries with a unique single origin from Rwanda to large chains such as Starbucks. There is a huge focus on quality and consistency; there are places, mainly in London, where they weight every shot of espresso (in and out) that they make.',
				 scandinavia: 'All of Scandinavia has been very active in the third coffee wave. Typical for the \'Scandinavian\' or \'Nordic\' roast is that it is in general a very light roast, were filtercoffee beans are barely being roasted after the \'the first crack\'. This is the moment in the roasting process where the first gasses escape from beans, thereby causing them to, quite literally, crack. ',
				 japan: 'Although Japan\'s coffee culture has existed since a Dutch man brought it to Nagasaki in the 19th century, it did not really boom until the 1970\'s. Since then, it has grown explosively, with lots of coffeehouses being opened. Too of the biggest players in the filter coffee market, Hario and Kalita, originate from Japan. ',
				 unitedStatesThird: 'Although Starbucks was, and still is, by far the biggest player in the specialty coffee, they did remain focussed on espresso-based coffees, especially the flavoured and frozen specials, instead of also joining the renewed interest in filter coffees. This left room for smaller business to fill this market, of which some by now have grown to chains themselves, such as Intelligentsia Coffee in Chicago and Blue Bottle Coffee in Oakland. Typical for the American coffee culture are the large pots or tanks of filtercoffee from which you can pull your own cup of coffee, and the usually very large sizes. Also, in 1982, the Specialty Coffee Association of America was founded, and they were the first to create a grading scheme to decide on whether a particular coffee was a \'specialty coffee\'.',
				 australia: 'Australia is the country were they \'invented\' the flat white; an espresso-based beverage, similar to latte, but with less milk, thus having a espresso-to-milk ratio somewhere between a latte and a cortado. Where the American coffee culture focuses on large amounts of coffee, the Australian coffee culture focusses on single, smaller cups of coffee, making one coffee at the time. In this way this culture is similar to the European culture, although the Australians tend to using darker roasts, especially compared to Scaninavia.'};
